name: parallel-jobs-actions-workflow
on: push
jobs:
  example-job-a:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: run script
        run: |
          bash ./run.sh
      - name: Retrieve IP
        run: |
          ifconfig -a
  example-job-b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run script
        run: |
          bash ./run.sh
      - name: Retrieve IP
        run: |
          ifconfig -a
